version: '3.9'

services:
  db:
    container_name: cryptoDB
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=crypto_base
      - PGDATA=/data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5    
    volumes:
      - /Users/nmaslenko/Programmings/mountpoints/DBCrypto:/data/postgres
  
  migrate:
    image: migrate/migrate
    profiles: ["tools"]
    volumes:
      - ./deployment/migrations/postgres:/migrations
    entrypoint:
      [
        "migrate",
        "-path",
        "/migrations",
        "-database",
        "postgres://postgres:postgres@db:5432/crypto_base?sslmode=disable",
      ]
    command: ["up"]
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure



volumes:
  postgres_data:
