// Code generated by MockGen. DO NOT EDIT.
// Source: ./client.go

// Package testdata is a generated GoMock package.
package testdata

import (
	context "context"
	reflect "reflect"

	entities "github.com/NViktorovich/cryptobackend/internal/entities"
	gomock "github.com/golang/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// GetCurrentRate mocks base method.
func (m *MockClient) GetCurrentRate(ctx context.Context, titles []string) ([]*entities.Crypto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentRate", ctx, titles)
	ret0, _ := ret[0].([]*entities.Crypto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentRate indicates an expected call of GetCurrentRate.
func (mr *MockClientMockRecorder) GetCurrentRate(ctx, titles interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentRate", reflect.TypeOf((*MockClient)(nil).GetCurrentRate), ctx, titles)
}
