// Code generated by MockGen. DO NOT EDIT.
// Source: ./storage.go

// Package testdata is a generated GoMock package.
package testdata

import (
	context "context"
	reflect "reflect"

	entities "github.com/NViktorovich/cryptobackend/internal/entities"
	gomock "github.com/golang/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// GetList mocks base method.
func (m *MockStorage) GetList(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetList", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetList indicates an expected call of GetList.
func (mr *MockStorageMockRecorder) GetList(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetList", reflect.TypeOf((*MockStorage)(nil).GetList), ctx)
}

// ReadAvg mocks base method.
func (m *MockStorage) ReadAvg(ctx context.Context, titles []string) ([]entities.Crypto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAvg", ctx, titles)
	ret0, _ := ret[0].([]entities.Crypto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAvg indicates an expected call of ReadAvg.
func (mr *MockStorageMockRecorder) ReadAvg(ctx, titles interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAvg", reflect.TypeOf((*MockStorage)(nil).ReadAvg), ctx, titles)
}

// ReadLast mocks base method.
func (m *MockStorage) ReadLast(ctx context.Context, titles []string) ([]entities.Crypto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadLast", ctx, titles)
	ret0, _ := ret[0].([]entities.Crypto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadLast indicates an expected call of ReadLast.
func (mr *MockStorageMockRecorder) ReadLast(ctx, titles interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadLast", reflect.TypeOf((*MockStorage)(nil).ReadLast), ctx, titles)
}

// ReadMax mocks base method.
func (m *MockStorage) ReadMax(ctx context.Context, titles []string) ([]entities.Crypto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadMax", ctx, titles)
	ret0, _ := ret[0].([]entities.Crypto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadMax indicates an expected call of ReadMax.
func (mr *MockStorageMockRecorder) ReadMax(ctx, titles interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadMax", reflect.TypeOf((*MockStorage)(nil).ReadMax), ctx, titles)
}

// ReadMin mocks base method.
func (m *MockStorage) ReadMin(ctx context.Context, titles []string) ([]entities.Crypto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadMin", ctx, titles)
	ret0, _ := ret[0].([]entities.Crypto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadMin indicates an expected call of ReadMin.
func (mr *MockStorageMockRecorder) ReadMin(ctx, titles interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadMin", reflect.TypeOf((*MockStorage)(nil).ReadMin), ctx, titles)
}

// UpdateList mocks base method.
func (m *MockStorage) UpdateList(ctx context.Context, title string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateList", ctx, title)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateList indicates an expected call of UpdateList.
func (mr *MockStorageMockRecorder) UpdateList(ctx, title interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateList", reflect.TypeOf((*MockStorage)(nil).UpdateList), ctx, title)
}

// Write mocks base method.
func (m *MockStorage) Write(ctx context.Context, cryptos []entities.Crypto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", ctx, cryptos)
	ret0, _ := ret[0].(error)
	return ret0
}

// Write indicates an expected call of Write.
func (mr *MockStorageMockRecorder) Write(ctx, cryptos interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockStorage)(nil).Write), ctx, cryptos)
}
