basePath: /crypto/v1/
definitions:
  dto.Crypto:
    properties:
      cost:
        type: number
      shortTitle:
        type: string
      timeStamp:
        type: string
      title:
        type: string
    type: object
  dto.Error:
    properties:
      message:
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  title: Simple Crypro API
  version: 1.0.0
paths:
  /getAvg:
    get:
      consumes:
      - application/json
      description: avg rates known cryptos
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.Crypto'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.Error'
      summary: avg rates known cryptos
      tags:
      - crypto
  /getLast:
    get:
      consumes:
      - application/json
      description: last rates known cryptos
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.Crypto'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.Error'
      summary: last rates known cryptos
      tags:
      - crypto
  /getMax:
    get:
      consumes:
      - application/json
      description: max rates known cryptos
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.Crypto'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.Error'
      summary: max rates known cryptos
      tags:
      - crypto
  /getMin:
    get:
      consumes:
      - application/json
      description: min rates known cryptos
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.Crypto'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.Error'
      summary: min rates known cryptos
      tags:
      - crypto
swagger: "2.0"
